
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author felip
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        P.add(new Disparo("Lechugas", "Verde", "Medio", "Lechuga", 300, 400));
        P.add(new Disparo("Guisante", "Verde", "Alto", "Guisantralladora", 100, 500));
        P.add(new Defensa(100, 80, 300, "Bajo", "Nuez", 0, 700));
        P.add(new Disparo("Pincho", "Rojo", "Medio", "Cactus", 70, 500));
        P.add(new Explosiva(500, "Bajo", "Patatapum", 100, 200));
        
        Z.add(new Clasico(3, new Bandera("Rojo", "DiscoC"), "Clasico", 100, 400));
        ArrayList<String> Comidos = new ArrayList();
        Comidos.add("Bryan");
        Comidos.add("Diego");
        Comidos.add("Alex");
        Z.add(new Cargado(170, 35, 14, Comidos, "Furioso", 150, 200));
        Z.add(new Clasico(30, new Bandera("Rojo", "DiscoD"), "Zombiestein", 2000, 700));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttong_Rang = new javax.swing.ButtonGroup();
        buttong_TypP = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        sp_Ata = new javax.swing.JTabbedPane();
        T_Test = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        PlantName = new javax.swing.JLabel();
        ZombieName = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Btn_Test = new javax.swing.JButton();
        T_Plantas = new javax.swing.JPanel();
        Txt_Rang = new javax.swing.JLabel();
        Txt_TipoP = new javax.swing.JLabel();
        Txt_NomP = new javax.swing.JLabel();
        Txt_AtkP = new javax.swing.JLabel();
        Txt_HpP = new javax.swing.JLabel();
        Txt_Mexp = new javax.swing.JLabel();
        Txt_Projectile = new javax.swing.JLabel();
        Txt_ColorP = new javax.swing.JLabel();
        Txt_Alt = new javax.swing.JLabel();
        Txt_Peso = new javax.swing.JLabel();
        Txt_Dureza = new javax.swing.JLabel();
        Btn_CreateP = new javax.swing.JButton();
        RB_Bajo = new javax.swing.JRadioButton();
        RB_Medio = new javax.swing.JRadioButton();
        RB_Alto = new javax.swing.JRadioButton();
        RB_Explosiva = new javax.swing.JRadioButton();
        RB_Disparo = new javax.swing.JRadioButton();
        RB_Defensa = new javax.swing.JRadioButton();
        tf_NameP = new javax.swing.JTextField();
        sp_Mexp = new javax.swing.JSpinner();
        tf_NameProj = new javax.swing.JTextField();
        tf_Color = new javax.swing.JTextField();
        sp_Alt = new javax.swing.JSpinner();
        sp_Peso = new javax.swing.JSpinner();
        sp_Dureza = new javax.swing.JSpinner();
        sp_AtkP = new javax.swing.JSpinner();
        sp_HpP = new javax.swing.JSpinner();
        T_Zombies = new javax.swing.JPanel();
        Txt_NomZ = new javax.swing.JLabel();
        Txt_Age = new javax.swing.JLabel();
        Txt_Rage = new javax.swing.JLabel();
        Txt_AtkZ = new javax.swing.JLabel();
        Txt_Size = new javax.swing.JLabel();
        Txt_AddPer = new javax.swing.JLabel();
        Txt_HpZ = new javax.swing.JLabel();
        Txt_expage = new javax.swing.JLabel();
        Txt_TipoZ = new javax.swing.JLabel();
        Txt_ColorB = new javax.swing.JLabel();
        Txt_Direccion = new javax.swing.JLabel();
        tf_NameZ = new javax.swing.JTextField();
        sp_Edad = new javax.swing.JSpinner();
        sp_Enojo = new javax.swing.JSpinner();
        sp_AtkZ = new javax.swing.JSpinner();
        sp_Size = new javax.swing.JSpinner();
        tf_Per = new javax.swing.JTextField();
        Btn_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Nombes = new javax.swing.JTextArea();
        sp_HpZ = new javax.swing.JSpinner();
        sp_Expage = new javax.swing.JSpinner();
        RB_Clasico = new javax.swing.JRadioButton();
        RB_Cargado = new javax.swing.JRadioButton();
        Btn_CreateZ = new javax.swing.JButton();
        tf_ColorB = new javax.swing.JTextField();
        tf_Img = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PVZ");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PLANTS VS ZOMBIES");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Entidad");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Planta");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Defensa");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Bajo");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Medio");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Alto");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Explosivo");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Bajo");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Alto");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Medio");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Disparo");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Bajo");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Alto");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Medio");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Zombie");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Clasico");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Cargado");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jTree1);

        PlantName.setText("-----");

        ZombieName.setText("-----");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        Btn_Test.setText("Testear");
        Btn_Test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout T_TestLayout = new javax.swing.GroupLayout(T_Test);
        T_Test.setLayout(T_TestLayout);
        T_TestLayout.setHorizontalGroup(
            T_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_TestLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(T_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_TestLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(T_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PlantName, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(ZombieName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(T_TestLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(T_TestLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(Btn_Test, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        T_TestLayout.setVerticalGroup(
            T_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_TestLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(T_TestLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(PlantName)
                .addGap(18, 18, 18)
                .addComponent(ZombieName)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Test)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        sp_Ata.addTab("Test", T_Test);

        Txt_Rang.setText("Rango");

        Txt_TipoP.setText("Tipo");

        Txt_NomP.setText("Nombre");

        Txt_AtkP.setText("Ataque");

        Txt_HpP.setText("Vida");

        Txt_Mexp.setText("Magnitud de Explosion");

        Txt_Projectile.setText("Nombre Proyectil");

        Txt_ColorP.setText("Color");

        Txt_Alt.setText("Altura");

        Txt_Peso.setText("Peso");

        Txt_Dureza.setText("Dureza");

        Btn_CreateP.setText("Crear");
        Btn_CreateP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_CreateP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_CreatePMouseClicked(evt);
            }
        });
        Btn_CreateP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CreatePActionPerformed(evt);
            }
        });

        buttong_Rang.add(RB_Bajo);
        RB_Bajo.setText("Bajo");
        RB_Bajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_BajoActionPerformed(evt);
            }
        });

        buttong_Rang.add(RB_Medio);
        RB_Medio.setText("Medio");
        RB_Medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_MedioActionPerformed(evt);
            }
        });

        buttong_Rang.add(RB_Alto);
        RB_Alto.setText("Alto");

        buttong_TypP.add(RB_Explosiva);
        RB_Explosiva.setText("Explosiva");

        buttong_TypP.add(RB_Disparo);
        RB_Disparo.setText("Disparo");

        buttong_TypP.add(RB_Defensa);
        RB_Defensa.setText("Defensa");
        RB_Defensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_DefensaActionPerformed(evt);
            }
        });

        tf_NameP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NamePActionPerformed(evt);
            }
        });

        tf_NameProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NameProjActionPerformed(evt);
            }
        });

        tf_Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout T_PlantasLayout = new javax.swing.GroupLayout(T_Plantas);
        T_Plantas.setLayout(T_PlantasLayout);
        T_PlantasLayout.setHorizontalGroup(
            T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_PlantasLayout.createSequentialGroup()
                .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_PlantasLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Txt_Rang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(Txt_TipoP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_NomP)
                            .addComponent(tf_NameP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_HpP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_HpP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(T_PlantasLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(Btn_CreateP))
                            .addGroup(T_PlantasLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_AtkP)
                                    .addComponent(sp_AtkP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(T_PlantasLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sp_Mexp)
                            .addComponent(Txt_Mexp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Txt_Alt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_Alt))
                        .addGap(54, 54, 54)
                        .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_Projectile)
                            .addComponent(Txt_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_NameProj, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp_Dureza, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Dureza, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_ColorP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(T_PlantasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RB_Bajo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RB_Medio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RB_Alto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RB_Explosiva, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RB_Defensa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(T_PlantasLayout.createSequentialGroup()
                                .addComponent(RB_Disparo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        T_PlantasLayout.setVerticalGroup(
            T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_PlantasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Rang)
                    .addComponent(Txt_TipoP)
                    .addComponent(Txt_NomP)
                    .addComponent(Txt_AtkP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB_Bajo)
                    .addComponent(RB_Explosiva)
                    .addComponent(tf_NameP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_AtkP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB_Disparo)
                    .addComponent(RB_Medio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB_Defensa)
                    .addComponent(Txt_HpP)
                    .addComponent(RB_Alto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(T_PlantasLayout.createSequentialGroup()
                        .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_CreateP)
                            .addComponent(sp_HpP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(222, Short.MAX_VALUE))
                    .addGroup(T_PlantasLayout.createSequentialGroup()
                        .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Mexp)
                            .addComponent(Txt_Projectile)
                            .addComponent(Txt_ColorP))
                        .addGap(18, 18, 18)
                        .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sp_Mexp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_NameProj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Alt)
                            .addComponent(Txt_Peso)
                            .addComponent(Txt_Dureza))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(T_PlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sp_Alt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_Dureza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );

        sp_Ata.addTab("Plantas", T_Plantas);

        Txt_NomZ.setText("Nombre");

        Txt_Age.setText("Edad");

        Txt_Rage.setText("Enojo");

        Txt_AtkZ.setText("Ataque");

        Txt_Size.setText("Tamaño");

        Txt_AddPer.setText("Agregar Persona Comida");

        Txt_HpZ.setText("Vida");

        Txt_expage.setText("Años de Experiencia");

        Txt_TipoZ.setText("Tipo");

        Txt_ColorB.setText("Color Bandera");

        Txt_Direccion.setText("Direccion Imagen");

        tf_NameZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NameZActionPerformed(evt);
            }
        });

        tf_Per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_PerActionPerformed(evt);
            }
        });

        Btn_add.setText("+");
        Btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_addMouseClicked(evt);
            }
        });
        Btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_addActionPerformed(evt);
            }
        });

        Nombes.setEditable(false);
        Nombes.setColumns(20);
        Nombes.setRows(5);
        jScrollPane1.setViewportView(Nombes);

        RB_Clasico.setText("Clasico");
        RB_Clasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_ClasicoActionPerformed(evt);
            }
        });

        RB_Cargado.setText("Cargado");
        RB_Cargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_CargadoActionPerformed(evt);
            }
        });

        Btn_CreateZ.setText("Crear");
        Btn_CreateZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_CreateZMouseClicked(evt);
            }
        });
        Btn_CreateZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CreateZActionPerformed(evt);
            }
        });

        tf_ColorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ColorBActionPerformed(evt);
            }
        });

        tf_Img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ImgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout T_ZombiesLayout = new javax.swing.GroupLayout(T_Zombies);
        T_Zombies.setLayout(T_ZombiesLayout);
        T_ZombiesLayout.setHorizontalGroup(
            T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_ZombiesLayout.createSequentialGroup()
                .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(T_ZombiesLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(sp_Enojo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, T_ZombiesLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_ZombiesLayout.createSequentialGroup()
                                .addComponent(Txt_Rage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155))
                            .addGroup(T_ZombiesLayout.createSequentialGroup()
                                .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_HpZ, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_TipoZ, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sp_HpZ, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(T_ZombiesLayout.createSequentialGroup()
                                        .addComponent(RB_Cargado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Btn_CreateZ)))
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(T_ZombiesLayout.createSequentialGroup()
                                .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(T_ZombiesLayout.createSequentialGroup()
                                        .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Txt_NomZ)
                                            .addComponent(tf_NameZ, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(113, 113, 113)
                                        .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Txt_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sp_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(T_ZombiesLayout.createSequentialGroup()
                                        .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Txt_AtkZ)
                                            .addComponent(sp_AtkZ, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RB_Clasico, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(90, 90, 90)
                                        .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(T_ZombiesLayout.createSequentialGroup()
                                                .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sp_Size, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Txt_Size)
                                                    .addComponent(Txt_expage)
                                                    .addComponent(Txt_ColorB)
                                                    .addComponent(Txt_Direccion)
                                                    .addComponent(sp_Expage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                                .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Txt_AddPer)
                                                    .addComponent(tf_Per, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(T_ZombiesLayout.createSequentialGroup()
                                                .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tf_ColorB, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tf_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addComponent(Btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
        );
        T_ZombiesLayout.setVerticalGroup(
            T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_ZombiesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_NomZ)
                    .addComponent(Txt_Age)
                    .addComponent(Txt_Rage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_NameZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_Enojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_AtkZ)
                    .addComponent(Txt_Size)
                    .addComponent(Txt_AddPer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_AtkZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_Size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_add))
                .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_ZombiesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(T_ZombiesLayout.createSequentialGroup()
                        .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(T_ZombiesLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txt_HpZ)
                                    .addComponent(Txt_expage))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sp_HpZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sp_Expage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addComponent(Txt_ColorB)
                                .addGap(6, 6, 6)
                                .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txt_TipoZ)
                                    .addComponent(tf_ColorB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(RB_Clasico))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_ZombiesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_Direccion)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(T_ZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(T_ZombiesLayout.createSequentialGroup()
                                .addComponent(RB_Cargado)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(T_ZombiesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_Img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_CreateZ)))
                        .addContainerGap())))
        );

        sp_Ata.addTab("Zombies", T_Zombies);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(212, 212, 212))
            .addComponent(sp_Ata)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sp_Ata))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_CreatePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CreatePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_CreatePActionPerformed

    private void RB_BajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_BajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_BajoActionPerformed

    private void RB_MedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_MedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_MedioActionPerformed

    private void RB_DefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_DefensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_DefensaActionPerformed

    private void tf_NamePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NamePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NamePActionPerformed

    private void tf_NameProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NameProjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NameProjActionPerformed

    private void tf_ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ColorActionPerformed

    private void tf_NameZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NameZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NameZActionPerformed

    private void tf_PerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_PerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_PerActionPerformed

    private void Btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_addActionPerformed

    private void RB_ClasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_ClasicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_ClasicoActionPerformed

    private void RB_CargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_CargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_CargadoActionPerformed

    private void Btn_CreateZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CreateZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_CreateZActionPerformed

    private void tf_ColorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ColorBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ColorBActionPerformed

    private void tf_ImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ImgActionPerformed

    private void Btn_TestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_TestActionPerformed

    private void Btn_CreatePMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_CreatePMouseClicked
        // TODO add your handling code here:
        
        String Nombre = tf_NameP.getText();
        int Ataque = (int) sp_AtkP.getValue();
        int vida = (int) sp_HpP.getValue();
        String Rango = "";
        if(RB_Bajo.isSelected()){
            Rango = "Bajo";
        }else if(RB_Medio.isSelected()){
            Rango = "Medio";
        }else if(RB_Alto.isSelected()){
            Rango = "Alto";
        }
        
        int choice = 0;
        
        if(RB_Explosiva.isSelected()){
            choice = 1;
        }else if(RB_Disparo.isSelected()){
            choice = 2;
        }else if(RB_Defensa.isSelected()){
            choice = 3;
        }
        
        switch(choice){
            
            case 1:{
                
                int Magnitud = (int) sp_Mexp.getValue();
                
                Plantas plant = new Explosiva(Magnitud, Rango, Nombre, Ataque, vida);
                P.add(plant);
                
            }
            break;
            
            case 2:{
                
                String NombreP = tf_NameProj.getText();
                String Color = tf_Color.getText();
                
                Plantas plant = new Disparo(NombreP, Color, Rango, Nombre, Ataque, vida);
                P.add(plant);
    
            }
            break;
            
            case 3:{
                
                int Altura = (int) sp_Alt.getValue();
                int Peso = (int) sp_Peso.getValue();
                int Dureza = (int) sp_Dureza.getValue();
    
                Plantas plant = new Defensa(Altura, Peso, Dureza, Rango, Nombre, Ataque, vida);
                P.add(plant);
            }
            break;
            
            default:
                
        }
        
        tf_NameP.setText("");
        sp_AtkP.setValue(0);
        sp_HpP.setValue(0);
        sp_Mexp.setValue(0);
        tf_NameProj.setText("");
        tf_Color.setText("");
        sp_Alt.setValue(0);
        sp_Peso.setValue(0);
        sp_Dureza.setValue(0);
        
        System.out.println(P.get(0).toString());
    }//GEN-LAST:event_Btn_CreatePMouseClicked

    private void Btn_CreateZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_CreateZMouseClicked
        // TODO add your handling code here:
        
        String Nombre = tf_NameZ.getText();
        int Ataque = (int) sp_AtkZ.getValue();
        int vida = (int) sp_HpZ.getValue();
        
        int choice = 0;
        if(RB_Clasico.isSelected()){
            choice = 1;
        }else if(RB_Cargado.isSelected()){
            choice = 2;
        }
        
        switch(choice){
            
            case 1:{
                int exp = (int) sp_Expage.getValue();
                Bandera b = new Bandera(tf_ColorB.getText(), tf_Img.getText());
                
                Zombies zom = new Clasico(exp, b, Nombre, Ataque, vida);
                Z.add(zom);
            }
            break;
            
            case 2:{
                int tamaño = (int) sp_Size.getValue();
                int edad = (int) sp_Edad.getValue();
                int enojo = (int) sp_Enojo.getValue();
                ArrayList<String> Personas = new ArrayList();
                
            }
            break;
        }
        tf_NameZ.setText("");
        sp_AtkZ.setValue(0);
        sp_HpZ.setValue(0);
        sp_Expage.setValue(0);
        tf_ColorB.setText("");
        tf_Img.setText("");
        Nombes.setText("");
    }//GEN-LAST:event_Btn_CreateZMouseClicked

    private void Btn_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_addMouseClicked
        // TODO add your handling code here:
        String Person = tf_Per.getText();
        
        Nombes.append(Person + "\n");
        tf_Per.setText("");
    }//GEN-LAST:event_Btn_addMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    ArrayList<Plantas> P = new ArrayList();
    ArrayList<Zombies> Z = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_CreateP;
    private javax.swing.JButton Btn_CreateZ;
    private javax.swing.JButton Btn_Test;
    private javax.swing.JButton Btn_add;
    private javax.swing.JTextArea Nombes;
    private javax.swing.JLabel PlantName;
    private javax.swing.JRadioButton RB_Alto;
    private javax.swing.JRadioButton RB_Bajo;
    private javax.swing.JRadioButton RB_Cargado;
    private javax.swing.JRadioButton RB_Clasico;
    private javax.swing.JRadioButton RB_Defensa;
    private javax.swing.JRadioButton RB_Disparo;
    private javax.swing.JRadioButton RB_Explosiva;
    private javax.swing.JRadioButton RB_Medio;
    private javax.swing.JPanel T_Plantas;
    private javax.swing.JPanel T_Test;
    private javax.swing.JPanel T_Zombies;
    private javax.swing.JLabel Txt_AddPer;
    private javax.swing.JLabel Txt_Age;
    private javax.swing.JLabel Txt_Alt;
    private javax.swing.JLabel Txt_AtkP;
    private javax.swing.JLabel Txt_AtkZ;
    private javax.swing.JLabel Txt_ColorB;
    private javax.swing.JLabel Txt_ColorP;
    private javax.swing.JLabel Txt_Direccion;
    private javax.swing.JLabel Txt_Dureza;
    private javax.swing.JLabel Txt_HpP;
    private javax.swing.JLabel Txt_HpZ;
    private javax.swing.JLabel Txt_Mexp;
    private javax.swing.JLabel Txt_NomP;
    private javax.swing.JLabel Txt_NomZ;
    private javax.swing.JLabel Txt_Peso;
    private javax.swing.JLabel Txt_Projectile;
    private javax.swing.JLabel Txt_Rage;
    private javax.swing.JLabel Txt_Rang;
    private javax.swing.JLabel Txt_Size;
    private javax.swing.JLabel Txt_TipoP;
    private javax.swing.JLabel Txt_TipoZ;
    private javax.swing.JLabel Txt_expage;
    private javax.swing.JLabel ZombieName;
    private javax.swing.ButtonGroup buttong_Rang;
    private javax.swing.ButtonGroup buttong_TypP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTree jTree1;
    private javax.swing.JSpinner sp_Alt;
    private javax.swing.JTabbedPane sp_Ata;
    private javax.swing.JSpinner sp_AtkP;
    private javax.swing.JSpinner sp_AtkZ;
    private javax.swing.JSpinner sp_Dureza;
    private javax.swing.JSpinner sp_Edad;
    private javax.swing.JSpinner sp_Enojo;
    private javax.swing.JSpinner sp_Expage;
    private javax.swing.JSpinner sp_HpP;
    private javax.swing.JSpinner sp_HpZ;
    private javax.swing.JSpinner sp_Mexp;
    private javax.swing.JSpinner sp_Peso;
    private javax.swing.JSpinner sp_Size;
    private javax.swing.JTextField tf_Color;
    private javax.swing.JTextField tf_ColorB;
    private javax.swing.JTextField tf_Img;
    private javax.swing.JTextField tf_NameP;
    private javax.swing.JTextField tf_NameProj;
    private javax.swing.JTextField tf_NameZ;
    private javax.swing.JTextField tf_Per;
    // End of variables declaration//GEN-END:variables
}
